@startuml
autonumber
skinparam ArrowColor #222
skinparam NoteBackgroundColor #FFFDE7
participant "Sistema Ágil" as Sistema_gil
participant "Grupo" as Grupo
participant "Automação GitHub" as Automa_o_GitHub
participant "Repositório" as Reposit_rio
title seq-pbl-23-encerramento-de-sprint
Sistema_gil -> Grupo : [A] Sinaliza fechamento
Automa_o_GitHub -> Reposit_rio : [B] Gera tag/release
@enduml
