@startuml
autonumber
skinparam ArrowColor #222
skinparam NoteBackgroundColor #FFFDE7
participant "Aluno" as Aluno
participant "Professor" as Professor
participant "LMS/Adalove" as LMS_Adalove
participant "Repositório" as Reposit_rio
title seq-pbl-03-solicita-revisao-de-nota
Aluno -> LMS_Adalove : [A] Abre pedido de revisão
LMS_Adalove -> Professor : [B] Encaminha pedido ao professor
Professor -> LMS_Adalove : [C] Atualiza/justifica nota
LMS_Adalove -> Aluno : [D] Notifica resultado da revisão
Aluno -> Reposit_rio : [E] Ajusta artefato (se solicitado)
@enduml
